before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
nfpms:
  -
    package_name: "{{ .ProjectName }}"
    vendor: Scott Jackson
    homepage: https://github.com/scottmmjackson/bb2todotxt
    maintainer: Scott Jackson <scottmmjackson@gmail.com>
    description: Converts pull request tasks from bitbucket to todo txt tasks
    license: BSD 3.0
    formats:
      - deb
      - rpm
      - termux.deb
      - archlinux
# Disable snapcrafts, they don't work
#snapcrafts:
#  -
#    publish:  false
#    summary: Converts pull request tasks from bitbucket to todo txt tasks
#    description: Converts pull request tasks from bitbucket to todo txt tasks
brews:
  -
    tap:
      owner: scottmmjackson
      name: homebrew-sj
      pull_request:
        enabled: true
        base: main
    folder: Formula
    homepage: "https://github.com/scottmmjackson/bb2todotxt"
    description: Converts pull request tasks from bitbucket to todo txt tasks
    test: |
      system "#{bin}/bb2todotxt -v"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
